version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm -v
      - node -v
      - npm install --no-progress -g serverless@3.35.2 --silent
      - npm install --save-dev serverless-python-requirements --silent
      - npm install --save-dev serverless-iam-roles-per-function --silent
      - apt-get update -qq && apt install python3-pip -y && apt install python3-venv -y && apt install python3-dev -y && apt install python3-virtualenv -y
      - pip install pipx
      - pipx install poetry
      - pipx inject poetry poetry-plugin

  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_SRC_DIR
      - poetry export --without-hashes -f requirements.txt -o requirements.txt --with-credentials
      - mkdir -p target/stg
      - serverless login
      - serverless package --package target/stg --stage stg -r ap-southeast-2 --verbose
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - buildspec-deploy.yml
  