version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 