app: job-scraper
org: pennycbb
service: job-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stackName: dev-job-scraper
  region: ap-southeast-2
  deploymentBucket:
    name: job-scraper-artifacts
    
custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  job-scraper:
    handler: job_scraper/main.lambda_handler
    name: job-scraping
    events:
      # Invoke Lambda function 
      - eventBridge:
          name: daily-job-post
          schedule: cron(00 06 ? * SUN-FRI *)
          description: "Daily Calls the Lambda function to scrape the website for the day"
          timezone: Pacific/Auckland

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function