service: job-scraper

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  environment:
    STAGE: ${opt:stage}
  stackName: job-scraper
  deploymentBucket:
    name: job-scraper-artifacts
    
custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false

package:
  exclude:
    - node_modules/**
    - package-lock.json
    - __pycache__
    - requirements

functions:
  job-scraper:
    handler: job_scraper/scraping.lambda_handler
    name: dev-job-scraping
    events:
      # Invoke Lambda function 
      - eventBridge:
          name: daily-job-post
          schedule: cron(00 06 ? * SUN-FRI *)
          description: "Daily Calls the Lambda function to scrape the website for the day"
          timezone: Pacific/Auckland
    iamRoleStatementsName: dev-job-scraper-role
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
        Resource:
          - "arn:aws:lambda:ap-southeast-2:011043691602:function:job-scraper:*"
          - "arn:aws:lambda:ap-southeast-2:011043691602:function:job-scraper"
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - "*"
      - Effect: "Allow"
        Action:
          - secretsmanager:GetSecretValue
        Resource:
          - "*"

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function